---
title: "Bolsa"
author: "Grupo Bolsa"
date: "2022-12-01"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Relatório da Bolsa de Valores do Brasil

Este relatório tem como objetivo analisar cinco ações diferentes da Bolsa de Valores do Brasil(B3).
O grupo responsável por esta análise é composto pelos seguintes integrantes:

- Airton Cândido;
- Thiago Lotufo;
- Wanderson Vitorino;
- Yuri Corrêa.

## Ações analisadas

As ações analisadas serão:

- EGIE3;
- GOLL4;
- PRIO3;
- GGBR4;
- MGLU3.

## Análise a ser realizada

A análise realizada será baseada no fechamento do dia de cada uma das ações, no período de de `2018` até `2022`.

Os cálculos são:

- Média;
- Mediana;
- Valor mínimo;
- Valor máximo;
- 

## Análise final

`r library(tidyquant)
library(dplyr)

tickers <- c("GGBR4.SA", "GOLL4.SA", "PRIO3.SA", "EGIE3.SA", "MGLU3.SA" )

start = "2018-01-01"
end = "2022-11-22"

prices <- tq_get(tickers, 
                  from = start,
                  to = end)`
                  
### Cálculos de açãos

`r 

egie3 <- prices  %>%
  filter(symbol == "EGIE3.SA")
  
goll4 <- prices  %>%
  filter(symbol == "GOLL4.SA")

prio3 <- prices  %>%
  filter(symbol == "PRIO3.SA")

ggbr4 <- prices  %>%
  filter(symbol == "GGBR4.SA")

mglu3 <- prices  %>%
  filter(symbol == "MGLU3.SA")

mean_egie3 <- mean(egie3$close, na.rm = TRUE)
median_egie3 <- median(egie3$close, na.rm = TRUE)
max_egie3 <- max(egie3$close)
min_egie3 <- min(egie3$close)

mean_goll4 <- mean(goll4$close, na.rm = TRUE)
median_goll4 <- median(goll4$close, na.rm = TRUE)
max_goll4 <- max(goll4$close)
min_goll4 <- min(goll4$close)

mean_prio3 <- mean(prio3$close, na.rm = TRUE)
median_prio3 <- median(prio3$close, na.rm = TRUE)
max_prio3 <- max(prio3$close)
min_prio3 <- min(prio3$close)

mean_ggbr4 <- mean(ggbr4$close, na.rm = TRUE)
median_ggbr4 <- median(ggbr4$close, na.rm = TRUE)
max_ggbr4 <- max(ggbr4$close)
min_ggbr4 <- min(ggbr4$close)

mean_mglu3 <- mean(mglu3$close, na.rm = TRUE)
median_mglu3 <- median(mglu3$close, na.rm = TRUE)
max_mglu3 <- max(mglu3$close)
min_mglu3 <- min(mglu3$close)

Índices <- c('Media', 'Mediana', 'Valor máximo', 'Valor mínimo')
EGIE3 <- c(mean_egie3, median_egie3, max_egie3, min_egie3)
GOLL4 <- c(mean_goll4, median_goll4, max_goll4, min_goll4)
PRIO3 <- c(mean_prio3, median_prio3, max_prio3, min_prio3)
GGBR4 <- c(mean_ggbr4, median_ggbr4, max_ggbr4, min_ggbr4)
MGLU3 <- c(mean_mglu3, median_mglu3, max_mglu3, min_mglu3)`

`r tabela_egie3 <- data.frame(Índices, EGIE3, GOLL4, PRIO3, GGBR4, MGLU3)``

`r tabela_egie3 %>% knitr::kable()`

## Diferença entre o máximo e mínimo.
## Valor da ação no primeiro dia analisado
## Valor da ação no último dia analisado
## Diferença entre ações